## Примеры к занятию N6 17.03.2016

![caption](files/pics/anatomyarrayrus.png "Рисунок 1 Шпаргалка по массивам в numpy")

In [16]:
# ЛИСТИНГ 1 Numpy

import numpy as np

shape1 = 30
a = np.arange(shape1)
print 'A', type(a), np.shape(a), a

# Изменение формы
shape2 = (3, 10)
b = a.reshape(shape2)
print 'B', type(b), np.shape(b), b

c = np.reshape(a, shape2[::-1])
print 'C', type(c), np.shape(c), c
# Анализ формы - рассмотрим оси или измерения

# Одномерный массив или вектор A
for i, v in enumerate(a.shape):
    print 'Array A -> axis %d: %d' % (i, v)
    
# Двумерный массив или матрица B
for i, v in enumerate(b.shape):
    print 'Array B -> axis %d: %d' % (i, v)
    

A <type 'numpy.ndarray'> (30L,) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]
B <type 'numpy.ndarray'> (3L, 10L) [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
C <type 'numpy.ndarray'> (10L, 3L) [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]
Array A -> axis 0: 30
Array B -> axis 0: 3
Array B -> axis 1: 10


In [38]:
# ЛИСТИНГ 2 Более сложные примеры reshape

import numpy as np

N = 24
shape1 = (4, 3, 2)
a = np.arange(N).reshape(shape1)

print 'A', a.shape

for i in a:
    for j in i:
        print '%s - %s - %s' % (a.shape, i.shape, j.shape,)

print 'A', a
        
shape2 = (2, 12)
b = a.reshape(shape2)
print 'B', b

# "Выравнивание" N-мерного массива в одномерный
c = a.flatten()
print 'C', c

A (4L, 3L, 2L)
(4L, 3L, 2L) - (3L, 2L) - (2L,)
(4L, 3L, 2L) - (3L, 2L) - (2L,)
(4L, 3L, 2L) - (3L, 2L) - (2L,)
(4L, 3L, 2L) - (3L, 2L) - (2L,)
(4L, 3L, 2L) - (3L, 2L) - (2L,)
(4L, 3L, 2L) - (3L, 2L) - (2L,)
(4L, 3L, 2L) - (3L, 2L) - (2L,)
(4L, 3L, 2L) - (3L, 2L) - (2L,)
(4L, 3L, 2L) - (3L, 2L) - (2L,)
(4L, 3L, 2L) - (3L, 2L) - (2L,)
(4L, 3L, 2L) - (3L, 2L) - (2L,)
(4L, 3L, 2L) - (3L, 2L) - (2L,)
A [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
B [[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
C [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [7]:
# ЛИСТИНГ 3 Некоторые функции numpy для создания массивов

import numpy as np

# linspace()
print 'linspace()'
x1 = np.linspace(0, 10, 50)
x2 = np.linspace(0, 10, 50, endpoint=False)

print 'X1: ', x1[0:5]
print 'X2: ', x2[5:15]

# arange()
print 'arange()'
x1 = np.arange(50, dtype='float')
x2 = np.arange(-10.5, 30.75, 2.7)

print 'X1: ', x1[0:5]
print 'X2: ', x2[5:15]

# random.random()
print 'random.random()'
x1 = np.random.random(50)
x2 = np.random.random((10, 24))

print 'X1: ', x1[0:5]
print 'X2: ', x2[5:15, 5]

# zeros()
print 'zeros()'
x1 = np.zeros(50, dtype=int)
x2 = np.zeros((10, 24))

print 'X1: ', x1[0:5]
print 'X2: ', x2[5:15, 5]

# ones()
print 'ones()'
x1 = np.ones(50)
x2 = np.ones((10, 24), dtype=int)

print 'X1: ', x1[0:5]
print 'X2: ', x2[5:15, 5]

linspace()
X1:  [ 0.          0.20408163  0.40816327  0.6122449   0.81632653]
X2:  [ 1.   1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6  2.8]
arange()
X1:  [ 0.  1.  2.  3.  4.]
X2:  [  3.    5.7   8.4  11.1  13.8  16.5  19.2  21.9  24.6  27.3]
random.random()
X1:  [ 0.20899928  0.89055935  0.62855137  0.61145394  0.5061542 ]
X2:  [ 0.07635859  0.15446729  0.68634205  0.80197473  0.70138603]
zeros()
X1:  [0 0 0 0 0]
X2:  [ 0.  0.  0.  0.  0.]
ones()
X1:  [ 1.  1.  1.  1.  1.]
X2:  [1 1 1 1 1]


In [18]:
# ЛИСТИНГ 4 Операции и срезы в массивах

import numpy as np

n = 15
x = np.arange(n)
y = 4.5*x - 13.6   # тоже массив
z = range(n)   # список

print 'X:', x[0:5]
print 'Y:', y[0:5]

ii = range(0, 10, 2)
print 'ii:', ii
print 'Y[ii]', y[ii]

# ***** ЭТО обработчик исключений *****
try:
    print 'Z[ii]', z[ii]
except:
    print u'От списка Z[ii] вектор-индекс взять нельзя!'
finally:
    print 'O.K.'
# ***** КОНЕЦ обработчика исключений *****

# Срез и вектор-индекс от двумерного массива
shape = (5, 13)
xy = np.random.random(shape)
print xy[2:4, ii].ndim, xy[2:4, ii].shape
print 'XY', xy[2:4, ii]

X: [0 1 2 3 4]
Y: [-13.6  -9.1  -4.6  -0.1   4.4]
ii: [0, 2, 4, 6, 8]
Y[ii] [-13.6  -4.6   4.4  13.4  22.4]
Z[ii] От списка Z[ii] вектор-индекс взять нельзя!
O.K.
2 (2L, 5L)
XY [[ 0.32505714  0.84804555  0.67486799  0.53792313  0.62752782]
 [ 0.01439775  0.748697    0.3102447   0.46884149  0.82296861]]


In [6]:
# ЛИСТИНГ 5

s = 'Sasha'

def printer(s):
    print '%s' % s
    
printer(s)

# Функции класса называются методами

class MED():
    def __init__(self, s):
        self.printer2(s)
    def printer2(self, s):
        print s
        
med = MED(s)

Sasha
Sasha


In [8]:
# ЛИСТИНГ 6 return

def powerxy1(x, y):
    return x**y

def powerxy2(x, y):
    z = x**y
    zm = -x**y
    return z, zm
    
x = 2
y = 4

f1 = powerxy1(x, y)
print type(f1), f1

f2 = powerxy2(x, y)
print type(f2), f2

x1, y1 = powerxy2(x, y)
print type(x1), x1
print type(y1), y1

<type 'int'> 16
<type 'tuple'> (16, -16)
<type 'int'> 16
<type 'int'> -16


In [ ]:
# ЛИСТИНГ 7 Работа с типами данных в функциях

import math

# Неизменяемые типы данных
def hypo(a, b):
    a = a + 3
    b = b - 1
    c = math.sqrt(a**2 + b**2)
    return c

x = 35
y = 45

print '1 - BEFORE:', x, y
hypo(x, y)
print '1 - AFTER:', x, y

# Изменяемые типы данных
def change(a, xa, b, xb):
    if xa in a: 
        i = a.index(xa)
        a[i] = -99.
        
    if xb in b:
        b[xb] = '0'

x = range(34)
xa = 17
y = {'one':1, 'two':2, 'three':3}
ya = 'two'

print '2 - BEFORE:', x[15:20], y
change(x, xa, y, ya)
print '2 - AFTER:', x[15:20], y

# Изменяемые типы данных - массивы

import numpy as np

def achan(a):
    if len(a) > 10: 
        a[10] = -99
    else:
        a[0] = a[-1]

n = 20
a = np.arange(n)

print '3 - BEFORE:', a
achan(a)
print '3 - AFTER:', a

In [2]:
# ЛИСТИНГ 8 Обязательные и необязательные параметры

import math

def call_me(ans, name=u'дорогой пользователь'):
    '''
    нкция округляет все действительные числа до целых
    '''
    b = [11, 12]
    phone = raw_input(u'Здравствуйте, %s! Оставьте, пожалуйста, свой номер телефона (7 цифр):' % name)
    ans = False
    if not str(phone).isdigit():
        print u'Номер должен содержать только цифры!'
    else:
        if len(phone) < 7:
            print u'Номер слишком короткий!'
        elif len(phone) > 7:
            print u'Номер слишком длинный!'
        else:
            print u'Спасибо! Мы обязательно перезвоним вам!'
            ans = True
    return ans, b

ans = False
myname = u'Павел'
while not ans:
    ans, c = call_me(ans)
#    ans = call_me(ans, myname)
print c

Здравствуйте, дорогой пользователь! Оставьте, пожалуйста, свой номер телефона (7 цифр):1234567
Спасибо! Мы обязательно перезвоним вам!
[11, 12]


In [4]:
# ЛИСТИНГ 9 Типы передачи параметров функции

def f_sum(a=2, b=3, c=4): # Все параметры являются необязательными
    return a + b + c

print f_sum(20) # Позиционное присваивание
print f_sum(2, 3, 20) # Позиционное присваивание
print f_sum(c=20) # Присваивание по ключу
print f_sum(1, b=34) # Присваивание по ключу

27
25
25
39


![caption](files/pics/haver.gif "Рисунок 2 Формула гаверсинусов")

In [6]:
# ЛИСТИНГ 10 Формула гаверсинусов

import math

def haversine(origin, destination):
    '''
    Points are tuples of (latitude, longitude)
    '''
    lat1, lon1 = origin
    lat2, lon2 = destination
    radius = 6371. # km

    dlat = math.radians(lat2-lat1)
    dlon = math.radians(lon2-lon1)
    a = math.sin(dlat/2.) * math.sin(dlat/2.) + math.cos(math.radians(lat1)) \
        * math.cos(math.radians(lat2)) * math.sin(dlon/2.) * math.sin(dlon/2.)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1.-a))
    d = radius * c

    return d
TSK = (56.49, 84.95)   # 56°29′19″ с. ш. 84°57′08″ в. д.
MSK = (55.76, 37.61)  # 55°45′21″ с. ш. 37°37′04″ в. д.
SPB = (59.95, 30.61) # 59°57′00″ с. ш. 30°19′00″ в. д. (G) (O) (Я)

print u'От Москвы до Ленинграда %.2f км' % haversine(SPB, MSK)

От Москвы до Ленинграда 622.71 км


![caption](files/pics/corel.png "Рисунок 3 Формула расчёта коэффициента корреляции Пирсона")

In [22]:
# ЛИСТИНГ 11 Коэффициент корреляции Пирсона 

import random
import numpy as np

def pirson_cc(x, y):
    u'''
    Это строка документирования!
    Функция вычисляет для двух последовательностей \
    коэффициент корреляции Пирсона.
    
    Входящие параметры:
    ===================
    
    **x [ndarray]** - одномерный массив длины N;
    **y [ndarray]** - одномерный массив длины N;
    
    Результат выполнения функции:
    =============================
    **сс [float]** - коэффициент корреляции Пирсона.
    '''
    
    xm = x.mean()
    ym = y.mean()

    a = 0
    b1 = 0
    b2 = 0
    for xi, yi in zip(x, y):
        a += (xi - xm)*(yi - ym)
        b1 += (xi - xm)**2 
        b2 += (yi - ym)**2
    b = np.sqrt(b1*b2)
    
    cc = float(a)/b
    return cc

N = 60
# методы списка + модуль random
a = range(N)
random.shuffle(a)
a = np.array(a)

# модуль numpy
b = np.arange(N)
np.random.shuffle(b)

print a
print b
print 'CC from def cc: %.3f' % pirson_cc(a, b)
print 'CC from numpy: %.3f' % np.corrcoef(a, b)[0][1]

[49 29 12 28 16  7 59 32 50 13 31 41 37  4 23 44 52  5 38 14 45 34 48 54  3
 18 39 20 24 27 22 19  9 35 21 15  1 56 36 42 30  0  8 57 10 11 46 55 51 47
 33 25 53 17  2 40 26  6 43 58]
[53 40  1 32 39 35 46 34 13  4 21 37 18 29 31 47 17 57 49 15 26 56  8 16 54
 23 27 19 28 20 36 38 51 45 22 24 59  7 25 55 43  0 12  9 50 10 44 58  5 52
 14 33  3 30  2 42 48  6 41 11]
CC from def cc: 0.006
CC from numpy: 0.006


In [1]:
# ЛИСТИНГ 12 Import

import os, sys
import time

print u'Место установки интерпретатора Python: {}'.format(sys.prefix)

print u'А в этих папках Python ищет модули: {}'.format(sys.prefix)
for v in sys.path:
    j = sys.path.index(v)
    print j, v

Место установки интерпретатора Python: C:\Users\pashabanov\Anaconda2
0 
1 C:\Users\pashabanov\Anaconda2\python27.zip
2 C:\Users\pashabanov\Anaconda2\DLLs
3 C:\Users\pashabanov\Anaconda2\lib
4 C:\Users\pashabanov\Anaconda2\lib\plat-win
5 C:\Users\pashabanov\Anaconda2\lib\lib-tk
6 C:\Users\pashabanov\Anaconda2
7 c:\users\pashabanov\anaconda2\lib\site-packages\sphinx-1.3.5-py2.7.egg
8 c:\users\pashabanov\anaconda2\lib\site-packages\setuptools-20.1.1-py2.7.egg
9 C:\Users\pashabanov\Anaconda2\lib\site-packages
10 C:\Users\pashabanov\Anaconda2\lib\site-packages\cryptography-1.0.2-py2.7-win-amd64.egg
11 C:\Users\pashabanov\Anaconda2\lib\site-packages\win32
12 C:\Users\pashabanov\Anaconda2\lib\site-packages\win32\lib
13 C:\Users\pashabanov\Anaconda2\lib\site-packages\Pythonwin
14 C:\Users\pashabanov\Anaconda2\lib\site-packages\IPython\extensions
15 C:\Users\pashabanov\.ipython


In [12]:
# ЛИСТИНГ 13 From Import as

import sys

import numpy as np   # псевдоним
from numpy import random as rn   # импорт части модуля
from numpy.random import random as randx   # импорт функции под псевдонимом
from numpy.random import random # импорт функции

shapexy = (7, 12)
print 'np is a %s' % type(np)
z = rn.random(shapexy)
z = randx(shapexy)
z = random(shapexy)
print z[:3, :3]

'''
Функция dir() возвращает список имен объекта, а если объект не указан,
то список имен в текущей локальной области видимости.
'''
ilist = dir()   
ilist.sort()
print ilist

np is a <type 'module'>
[[ 0.35015817  0.13035735  0.41397556]
 [ 0.89803573  0.66833484  0.75356305]
 [ 0.09149152  0.67895228  0.25219487]]
['In', 'Out', '_', '__', '___', '__builtin__', '__builtins__', '__doc__', '__name__', '__package__', '_dh', '_i', '_i1', '_i10', '_i11', '_i12', '_i2', '_i3', '_i4', '_i5', '_i6', '_i7', '_i8', '_i9', '_ih', '_ii', '_iii', '_oh', '_sh', 'exit', 'get_ipython', 'i', 'ilist', 'j', 'modlist', 'np', 'numpy', 'os', 'quit', 'random', 'randx', 'rn', 'shapexy', 'sys', 'time', 'v', 'z']


In [22]:
# ЛИСТИНГ 14 Пакеты main1

# -*- coding: utf-8 -*-
"""
Created on Fri Mar 11 22:48:27 2016

@author: pasha
"""

import math
import random
import numpy as np

def haversine(origin, destination):
    '''
    Points are tuples of (latitude, longitude)
    '''
    lat1, lon1 = origin
    lat2, lon2 = destination
    radius = 6371. # km

    dlat = math.radians(lat2-lat1)
    dlon = math.radians(lon2-lon1)
    a = math.sin(dlat/2.) * math.sin(dlat/2.) + math.cos(math.radians(lat1)) \
        * math.cos(math.radians(lat2)) * math.sin(dlon/2.) * math.sin(dlon/2.)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1.-a))
    d = radius * c

    return d

def pirson_cc(x, y):
    u'''
    Это строка документирования!
    Функция вычисляет для двух последовательностей \
    коэффициент корреляции Пирсона.
    
    Входящие параметры:
    ===================
    
    **x [ndarray]** - одномерный массив длины N;
    **y [ndarray]** - одномерный массив длины N;
    
    Результат выполнения функции:
    =============================
    **сс [float]** - коэффициент корреляции Пирсона.
    '''
    
    xm = x.mean()
    ym = y.mean()

    a = 0
    b1 = 0
    b2 = 0
    for xi, yi in zip(x, y):
        a += (xi - xm)*(yi - ym)
        b1 += (xi - xm)**2 
        b2 += (yi - ym)**2
    b = np.sqrt(b1*b2)
    
    cc = float(a)/b
    return cc

# **************************************

N = 60
# методы списка + модуль random
a = range(N)
random.shuffle(a)
a = np.array(a)

# модуль numpy
b = np.arange(N)
np.random.shuffle(b)

TSK = (56.49, 84.95)   # 56°29′19″ с. ш. 84°57′08″ в. д.
MSK = (55.76, 37.61)  # 55°45′21″ с. ш. 37°37′04″ в. д.
SPB = (59.95, 30.61) # 59°57′00″ с. ш. 30°19′00″ в. д. (G) (O) (Я)

print u'От Москвы до Ленинграда %.2f км' % haversine(SPB, MSK)
print 'CC from def cc: %.3f' % pirson_cc(a, b)
print u'\n Сравни: \n'
print 'CC from numpy: %.3f' % np.corrcoef(a, b)[0][1]

От Москвы до Ленинграда 622.71 км
CC from def cc: -0.103

 Сравни: 

CC from numpy: -0.103


In [27]:
# ЛИСТИНГ 15 Пакеты main2

# -*- coding: utf-8 -*-
"""
Created on Fri Mar 11 22:48:27 2016

@author: pasha
"""

import os, sys
import random
import numpy as np

from progs.data import libf
from progs.data.meta.window import printer

N = 60
# методы списка + модуль random
a = range(N)
random.shuffle(a)
a = np.array(a)

# модуль numpy
b = np.arange(N)
np.random.shuffle(b)

TSK = (56.49, 84.95)   # 56°29′19″ с. ш. 84°57′08″ в. д.
MSK = (55.76, 37.61)  # 55°45′21″ с. ш. 37°37′04″ в. д.
SPB = (59.95, 30.61) # 59°57′00″ с. ш. 30°19′00″ в. д. (G) (O) (Я)

print u'От Москвы до Ленинграда %.2f км' % libf.haversine(SPB, MSK)
print 'CC from def cc: %.3f' % libf.pirson_cc(a, b)
print u'Текущее время %s' % printer()
#print 'CC from numpy: %.3f' % np.corrcoef(a, b)[0][1]

От Москвы до Ленинграда 622.71 км
CC from def cc: -0.044
Текущее время 2016-03-16-00-18-06
